# This template file will have its environment variables expanded
# and the .template extension removed by the bash-template Wercker step.
# See wercker.yml.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-jhk-deploy
  labels:
    #commit: ${WERCKER_GIT_COMMIT}
    app: my-jhk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-jhk
  template:
    metadata:
      labels:
        app: my-jhk
        #commit: ${WERCKER_GIT_COMMIT}
    spec:
      containers:
      - name: my-jhk-server
        image: iad.ocir.io/gse00014392/cpruvost:latest
        ports:
        - name: my-jhk-port
          containerPort: 8090
          protocol: TCP
      imagePullSecrets:
      - name: regcred