# This template file will have its environment variables expanded
# and the .template extension removed by the bash-template Wercker step.
# See wercker.yml.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: javahellokube
  labels:
    commit: ${WERCKER_GIT_COMMIT}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javahellokube
  template:
    metadata:
      labels:
        app: javahellokube
        commit: ${WERCKER_GIT_COMMIT}
    spec:
      containers:
      - name: javahlserver
        image: ${DOCKER_REPO}:${WERCKER_GIT_COMMIT}
        ports:
        - name: javahlserver
          containerPort: 8080
          protocol: TCP
      imagePullSecrets:
      - name:  ${OKE_IMAGESECRET}